services:
  app:
    build: .
    image: qr-service-dev
    container_name: qr-service-dev
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: qrdb
      DB_USER: postgres
      DB_PASS: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: 5a71a1ec2c314f79f732a1d9bd51fb32
      JWT_EXPIRATION: 3600000
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app  # Monta el código para desarrollo en caliente

  db:
    image: postgres:15
    container_name: qr-postgres
    environment:
      POSTGRES_DB: qrdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis:
    image: redis:7
    container_name: qr-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
  redis_data:
