spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:db}:${DB_PORT:5432}/${DB_NAME:qrdb}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
  jpa:
    hibernate:
      ddl-auto: update
  redis:
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}
  cache:
    type: redis